### ISSUE TITLE
Swedish translation

### ISSUE THREAD

**Issue by eson57** [steffen-foerster/sailfish-barcode#13]
Hi,
Thanks for this nice code reader. Do you want Swedish translation? Download from link below...
https://dl.dropboxusercontent.com/u/6697285/harbour-barcode-sv.ts

Åke Engelbrektson

**Comment by eson57** [comment]
Hi again,

I was contacted by a guy that wanted to submit a new translation (zh_TW), but couldn't find a way to do so. He wants me to send you the file, and as I can't find a way either, I've uploaded the file at my domain. You are very hard to get in contact with.  ;)

http://svenskasprakfiler.se/tempfiles/harbour-barcode-zh_TW.ts

**Comment by steffen-foerster** [comment]
Hi,

Thanks for the translation. 

By the way, here is my Twitter name: @stfowinti ;-)
