### ISSUE TITLE
[JollaC] camera to bright

### ISSUE THREAD

**Issue by Nokius** [steffen-foerster/sailfish-barcode#27]
The Camera is to bright in most environments.

![screenshot_20160722_001](https://cloud.githubusercontent.com/assets/879178/17057665/c80e7952-501b-11e6-8353-5d95e7d6e9f9.png)
This is taken indoor at work desk

**Comment by steffen-foerster** [comment]
I have created a new version. You can find it on openrepos.net. Please can you test it? I don't have a Jolla C.

**Comment by Nokius** [comment]
@steffen-foerster can't spot it :s

**Comment by steffen-foerster** [comment]
https://openrepos.net/content/steffenf/codereader

Please try it again :-)

**Comment by Nokius** [comment]
Looks much better

![screenshot_20160726_001](https://cloud.githubusercontent.com/assets/879178/17139417/9afe7558-5344-11e6-82bc-f4b963e9eb25.png)

**Comment by steffen-foerster** [comment]
Thanks for your support. I will create a new version for the Jolla store, too.

**Comment by Nokius** [comment]
np your are welcome 

Thank you for great application please let me know when you stop in Berlin to buy you a drink of choice

**Comment by steffen-foerster** [comment]
I'll take you up on that offer :-)
