### ISSUE TITLE
Support sms uri scheme

### ISSUE THREAD

**Issue by deram** [steffen-foerster/sailfish-barcode#9]
Please add possibility to open sms URL (rfc5724) by clicking (like http URL works).
Sailfish URL opener works correctly with them, by opening a sms sending dialog with preset recipient and message.

**Comment by deram** [comment]
Thanks for the feature. It works nicely when sending to normal numbers. Though it only works when using global numbers (starting with +).

RFC states the number may be either local or global numbers, so urls like sms:12345 should be matched too.

**Comment by deram** [comment]
also it does not work with ?body=fooobar prefilled messages. (I think making /^sms:.*$/ clickable should be fine)

**Comment by steffen-foerster** [comment]
Please check this feature with the new release 0.7.4.

Thanks,
Steffen

**Comment by deram** [comment]
thanks, now it works perfectly
